name: Build and Deploy Blazor WebAssembly

on:
  push:
    branches: [release]

  workflow_dispatch:

concurrency:
  group: build-and-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: release

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Create 404.html
        run: cp ./Blog/wwwroot/index.html ./Blog/wwwroot/404.html

      - name: Clone Posts and Scripts Repositories
        uses: actions/checkout@v5
        with:
          repository: YUBIZ/Posts
          path: ./Posts

      - uses: actions/checkout@v5
        with:
          repository: YUBIZ/Scripts
          path: ./Scripts

      - name: Copy Content
        run: cp -r ./Posts/* ./Blog/wwwroot

      - name: Run script
        run: |
          dotnet tool install -g dotnet-script
          dotnet script Scripts/Main.csx generate-file-path-and-commit-history-collection ./Blog/wwwroot/Docs ./Blog/wwwroot/document-file-path-and-commit-history-collection.json                                                            --exclude-patterns Docs/템플릿.md
          dotnet script Scripts/Main.csx generate-file-tree                               ./Blog/wwwroot/Docs ./Blog/wwwroot/document-file-tree.json                                                                                          --exclude-patterns Docs/템플릿.md
          dotnet script Scripts/Main.csx generate-site-map                                ./Blog/wwwroot/Docs ./Blog/wwwroot/document-site-map.xml                                  https://yubiz.github.io/PostView/Document?document-uri=   --exclude-patterns Docs/템플릿.md

      - name: Build Blazor WebAssembly
        run: |
          dotnet restore
          dotnet publish --no-restore -c Release --output ./publish

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./publish/wwwroot

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
