name: Build and Deploy Blazor WebAssembly

on:
  push:
    branches: [release]

  workflow_dispatch:

concurrency:
  group: build-and-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: release

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Create 404.html
        run: cp ./Blog/wwwroot/index.html ./Blog/wwwroot/404.html

      - name: Build Blazor WebAssembly
        run: |
          dotnet restore
          dotnet publish --no-restore -c Release

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./Blog/bin/Release/net9.0/publish/wwwroot

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
